name: Generate images.json

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'images/**'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Generate images.json
      run: python generate_images_json.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add images.json
        git commit -m 'Auto-generate images.json'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
